### ISSUE TITLE
When Todo icon is active due to RHS being open, the background is lightly darker than it should be

### ISSUE THREAD

**Issue by larkox** [mattermost/mattermost-plugin-todo#104]
As seen at the screenshot, there is some background color on the button that should not be there. The style should be fixed to fit the background.

![Screenshot from 2020-07-23 14-32-55](https://user-images.githubusercontent.com/1933730/88287027-08340400-ccf2-11ea-9195-9044969b5a42.png)
![Screenshot from 2020-07-23 14-30-09](https://user-images.githubusercontent.com/1933730/88287029-09fdc780-ccf2-11ea-9081-dbdb67926214.png)

**Comment by larkox** [comment]
@aidapira Since you worked on this feature, would you like to take on this one?

**Comment by larkox** [comment]
This also happen on the dropdown when it is active. Not sure what is our take on what should happen in the dropdown.

@asaadmahmood In the dropdown (the screenshot below) should we also highlight the icon if the RHS is open (like the screenshot above)?

![Screenshot from 2020-07-23 17-17-14](https://user-images.githubusercontent.com/1933730/88304709-e5f9b080-cd08-11ea-9455-77e809d4868e.png)

**Comment by asaadmahmood** [comment]
@larkox No, the icon in the dropdown should not be highlighted.

**Comment by colorfusion** [comment]
If the icon in the dropdown should be not highlighted, then we probably have to remove the highlighting of the icon from the plugin side instead. The highlighting can be feature added to the mattermost webapp itself to highlight channel header buttons that can be toggled instead.

**Comment by larkox** [comment]
@colorfusion The problem at the moment is not about the highlight, but about the icon having some weird background (the highlight should just change the color of the foreground).

**Comment by colorfusion** [comment]
The weird background comes from the `channel-header__icon--active` class attached to the `span` inside `channel_header_button.tsx` due to the dropdown rendering the same component `<ChannelHeaderButton/>. That same class is used to highlight the other icons (members / pins) when they are toggled, that's why the css has the background color attached to it. 

Are we looking at removing the background color and retaining the highlighted icon color when toggled?

**Comment by larkox** [comment]
Yes, that would be the objective.

**Comment by colorfusion** [comment]
I would like to work on this, if everyone's cool with it. 😎

**Comment by larkox** [comment]
All yours! Thank you very much!
