### ISSUE TITLE
Add System Console setting to allow disabling the LHS buttons

### ISSUE THREAD

**Issue by larkox** [mattermost/mattermost-plugin-todo#109]
Right now we are showing several buttons on the LHS. Add a setting on the system console to disable for all users.

**Comment by colorfusion** [comment]
Hey @larkox, I would like to give this a shot if you're cool with it.

**Comment by larkox** [comment]
All yours. If you need any help, do not hesitate to ask :smile:

**Comment by colorfusion** [comment]
Hey @larkox, regarding this issue. I assume I need to do the following
- Add new key into `settings` of `settings_schema` inside `plugin.json` file.
- Check key and only register `TeamSidebar` component through `registerBottomTeamSidebarComponent` if it's true.

I was looking through any snippet examples of reading the settings parameter in the webapp side, but I'm unable to find any examples. Do you have any idea how I can tackle this issue?

**Comment by larkox** [comment]
An easier way of dealing with this is registering always the TeamSidebar, but add some check to not show anything in case the setting is not set. To read the setting from the component, you might need to do something a bit more complicated, which will be exposing a new API endpoint to ask for that setting. In order to be up to date with the setting, I would fetch it (and store in the redux store) on initialization, and also add a webhook for the case where it changes.

What do you think?

**Comment by colorfusion** [comment]
That sounds like a good idea, I'll look into that.

May I get you to explain more in detail about the webhook part? I'm not 100% sure about how webhooks works in tracking of the changes in the setting.

**Comment by larkox** [comment]
Todo plugin is already using webhooks. I can link you here the relevant parts:
- Webhook creation: https://github.com/mattermost/mattermost-plugin-todo/blob/1905ad536a12464b850c7991dde55f71fd7b4b2c/webapp/src/index.js#L40
- Webhook function implementation (mainly dispatching redux actions): https://github.com/mattermost/mattermost-plugin-todo/blob/1905ad536a12464b850c7991dde55f71fd7b4b2c/webapp/src/index.js#L34
- Server side webhook event creation: https://github.com/mattermost/mattermost-plugin-todo/blob/1905ad536a12464b850c7991dde55f71fd7b4b2c/server/plugin.go#L398
- Server side use example: https://github.com/mattermost/mattermost-plugin-todo/blob/1905ad536a12464b850c7991dde55f71fd7b4b2c/server/plugin.go#L394

Probably, the idea would be to broadcast to all users, not only to a single one. The place to call the event I think would be "OnConfigurationChange".

**Comment by colorfusion** [comment]
Thanks a lot for the snippets! I'll work on the issue with those references.
