### ISSUE TITLE
Option to disable daily reminders

### ISSUE THREAD

**Issue by michaelkozakovsc** [mattermost/mattermost-plugin-todo#120]
I often add todos that are not due for weeks - getting a daily rundown gets very annoying. My suggestions:

1) option to disable daily reminder message
2) more options to configure notifications

**Comment by larkox** [comment]
We recently added (to version 0.4.0) a slash command to disable daily reminders. Just type `/todo settings summary off` and it should be removed. Let me know if that worked for you.
