### ISSUE TITLE
Feature Request: Make telemetry opt-in

### ISSUE THREAD

**Issue by merspieler** [mattermost/mattermost-plugin-todo#122]
I'm missing the ability to opt-in/out of the telemetry collection.

If there's telemetry collected the users should as well be made aware of it.

**Comment by aaronrothschild** [comment]
The server controls the telemetry sent by the plugins - if an admin has set the server to not send telemetry - the plugin will not send it either.

**Comment by merspieler** [comment]
I'm an admin and I don't see any option to disable telemetry

**Comment by merspieler** [comment]
So, where can I opt out?

**Comment by larkox** [comment]
@merspieler If I am not mistaken, the setting you are looking for is "Enable Diagnostics and Error Reporting" in the System Console.

**Comment by merspieler** [comment]
@larkox oh... now I get it... it follows the global setting... thanks.
