### ISSUE TITLE
Release 0.5.0

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-plugin-todo#128]
- [x] https://github.com/mattermost/mattermost-plugin-todo/pull/127

**Comment by hanzei** [comment]
@larkox Is there anything else you want to get in?

**Comment by larkox** [comment]
No. That seems like all needed. Thanks :smile:

**Comment by moschlar** [comment]
Ping?

**Comment by hanzei** [comment]
@larkox Would you be open on taking care of the release?

**Comment by larkox** [comment]
@hanzei Sure, I will take it.
