### ISSUE TITLE
Does it support localization?

### ISSUE THREAD

**Issue by burnelltw** [mattermost/mattermost-plugin-todo#131]
if it support localization,
I can help with translate it to other languages.
Thanks a lot.

**Comment by larkox** [comment]
Thanks for the comment @burnelltw . Right now it does not support localization. Nevertheless, if you are interested in the localization of other parts of the product, feel free to check join this channel in the community server: https://community.mattermost.com/core/channels/localization

**Comment by larkox** [comment]
Any progress in the localization support for this plugin will be registered in the #134 issue.
