### ISSUE TITLE
Sidebar UI elements not visible on Web clients (403 on loading js for plugin_com.mattermost.plugin-todo)

### ISSUE THREAD

**Issue by rummens** [mattermost/mattermost-plugin-todo#147]
Hi there,

since a few versions we are facing an issue that the UI elements to open the TODO menus are not visible in the web interface of MM (even in different browsers). It is however in the local client for at least Mac and Linux (did not test Windows yet). We've been hoping for a fix in the last few versions but the error persists. 

Any idea what could go wrong and how we can troubleshoot the issue? The console points me to a .js. file which cannot be loaded because of a 403. Could there be something wrong with the Auth part to not allow the serving of this file?

We are running Version **4.5.2 (4.5.2.6864)**. 

Mac/Linux Client:
<img width="70" alt="image" src="https://user-images.githubusercontent.com/31141785/140541741-22deac95-5b43-45ac-8f42-3dbe220ab16f.png">

Web Client:
<img width="88" alt="image" src="https://user-images.githubusercontent.com/31141785/140541800-afd5975d-cf42-4380-8651-719172308591.png">

Safari Console output (Version 15.0 (16612.1.29.41.4, 16612))
![image](https://user-images.githubusercontent.com/13119842/140743150-a4a496b3-6c5e-43f9-a891-4dcf490e4ad8.png)

Thank you very much
Marcel

**Comment by larkox** [comment]
Is there any chance that any kind of firewall (be it on the browser, server, or connection) is limiting the access to the plugin code only for the web client and not from the desktop client?

**Comment by rummens** [comment]
There is not, we have not deployed any WAF or similar between MM and the clients. There is a normal FW but it allows full access to MM, as long as these specific js files are not loaded using a different port or protocol, the FW should not be the issue.

Is there a config in MM to allow/deny certain files or extensions?

**Comment by jasonblais** [comment]
@rummens thanks for your report! Noticed it included your site URL / domain in the console output - I redacted and re-pasted into the description, hope that was okay! Wanted to do it in case it was confidential :)

**Comment by rummens** [comment]
> @rummens thanks for your report! Noticed it included your site URL / domain in the console output - I redacted and re-pasted into the description, hope that was okay! Wanted to do it in case it was confidential :)

Cheers. appreciate it.

**Comment by larkox** [comment]
@hanzei Do you have any idea why this issue may be happening?

**Comment by hanzei** [comment]
@rummens Are you running v4.5 of Mattermost? If so, that is a quite outdated one.

**Comment by rummens** [comment]
I think what I copied was the app version. Server runs  6.02

> @rummens Are you running v4.5 of Mattermost? If so, that is a quite outdated one.

**Comment by hanzei** [comment]
@rummens  What is the content-type of the plugin bundle? You can find that information under `Network` by searching for `todo`.

**Comment by rummens** [comment]
It seems that the latest release (6.1.0) has fixed the issue, at least for web clients. It required a reset of browser settings and cache but so far I am getting positive responses from our users.

Thanks for the help.

**Comment by mickmister** [comment]
Hi @rummens, do you happen to be running a proxy in front of your server? Also just to try and diagnose the issue, are you able to test what the content type of the response is when the issue is occurring versus when it is working properly?

**Comment by rummens** [comment]
Yes we did/do have a VPX/LB in between. If you tell me how I can look it up I can let you know. I looked into the Network tab in my browser but it didn't include any interesting headers.
