### ISSUE TITLE
when i click on the search box of TODO then i'm getting the blank screen 

### ISSUE THREAD

**Issue by dipak-demansol** [mattermost/mattermost-plugin-todo#149]
#### Summary
when i click on the search box of TODO then i'm getting the blank screen 

#### Steps to reproduce
Steps :- 1) Click on the TODO icon.
             2) click on "add new TODO btn/label"
             3) Click on the search input box to invite the user.

#### Expected behavior
   :- The user should not Get the blank screen, he should able to invite/ search the user.

https://user-images.githubusercontent.com/89907719/146809910-fb46c3d6-39ad-462a-9ab4-1d937161cde8.mp4

![Screenshot from 2021-12-20 23-16-11](https://user-images.githubusercontent.com/89907719/146810106-4c2886eb-4959-41d0-b0a1-b141bc036fa9.png)

**Comment by jprusch** [comment]
Cannot reproduce on MM 6.2.0 with ToDo 0.4.0 with Windows Desktop 5.0.2 & Chrome Browser.

**Comment by dipak-demansol** [comment]
> Cannot reproduce on MM 6.2.0 with ToDo 0.4.0 with Windows Desktop 5.0.2 & Chrome Browser.

@jprusch
issue generate in the Community https://community.mattermost.com/
```
Mattermost Version: cloud-2021-12-08-1
Database Schema Version: 6.3.0
```

**Comment by hanzei** [comment]
@dipak-demansol can you please try to reproduce this issue against `master'?

**Comment by dipak-demansol** [comment]
> @dipak-demansol can you please try to reproduce this issue against `master'?

Testing Done, Issue Not Generated With The Master Branch, BUt Still Issue Generate in The Production (Core, 6.4.0)

**Comment by hanzei** [comment]
@dipak-demansol What do you mean with `in The Production`?

**Comment by dipak-demansol** [comment]
> @dipak-demansol What do you mean with `in The Production`?

@hanzei i mean https://community.mattermost.com/core/

**Comment by hanzei** [comment]
@dipak-demansol Can you check again please?

**Comment by dipak-demansol** [comment]
> @dipak-demansol Can you check again please?

@hanzei Now This issue Is Not Generated In the mattermost 6.5.0 Version.
