### ISSUE TITLE
Various plugin on Community throw JS errors after upgrading to version 0.5.0 

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-todo#155]
After upgrading the community server to version `v0.5.0` of the ToDo plugin, many users reported seeing multiple JS errors from various plugins. 
The errors seem to mostly show `[Util] handleerror:: Uncaught TypeError: Cannot read property of undefined (reading 'data')`
![image](https://user-images.githubusercontent.com/35588783/149843058-f028ec65-0e2f-4f6c-b3f6-5cc0881b4f1e.png)
![image](https://user-images.githubusercontent.com/35588783/149843482-aedab066-9f65-4b73-82f9-3c312881218c.png)

These error then stopped occurring once the plugin was downgraded again to `v0.4.0`. 

I have not yet found local reproduction steps for this set of errors but, this must be investigated and resolved.

**Comment by DHaussermann** [comment]
I don't have steps yet. but I did see this locally after the plugin was running server `release-6.3)`
As also mentioned in the thread on community - I could **not** dismiss the developer mode JS error banner.  

![image](https://user-images.githubusercontent.com/35588783/149975408-fc5fffa6-6440-4e20-aba2-7258a0e87d85.png)

Not in the tooltip that the error is originating prom the ToDo plugin and showing this path `com.mattermost.plugin-todo_aac754197b06c376_bundle.js`.

When I follow the link in the browser console the following is highlighted. 

```
o=({data:{lists:e}})=>e.forEach(e=>t.dispatch(O(!1,(e=>{let t="my";switch(e){case"":t="my";break;case"_in":t="in";break;case"_out":t="out";break;default:t="my"}return t})(e))));e.registerWebSocketEventHandler("custom_".concat(a,"_refresh"),o),e.registerReconnectHandler(o),t.dispatch(O(!0)),t.dispatch(O(!1,"in")),t.dispatch(O(!1,"out"));e.registerWebSocketEventHandler("custom_".concat(a,"_config_update"),({data:e})=>{t.dispatch(U(e.hide_team_sidebar))}),t.dispatch(async(e,t)=>{let n,r;try{n=await fetch(R(t())+"/config",c.Client4.getOptions({method:"get"})),r=await n.json()}catch(e){return{error:e}}return e(U(r.hide_team_sidebar)),{data:r}}),bi=()=>{const e=(new Date).getTime();e-Ri>36e5&&t.dispatch(O(!0)),Ri=e},document.addEventListener("click",bi),e.registerPostTypeComponent("custom_todo",hi)}deinitialize(){document.removeEventListener("click",bi)}}window.registerPlugin(a,new Ii)}]);
```

**Comment by larkox** [comment]
That seems to be on `webapp/src/index.js:64`. Here we are not handling the possibility of an error in the dispatcher, and can cause this. Not sure if the reason, or a symptom of something else failing. A first take on this would be to rewrite this so the error is handled, and test again so we can see what error we are receiving, and see what is the actual culprit.

**Comment by joebordes** [comment]
should we downgrade while we wait?

**Comment by hanzei** [comment]
https://github.com/mattermost/mattermost-plugin-todo/blob/cda33503b0ad334d3a86dc6921e562d901e8e40a/webapp/src/index.js#L64 could be the line causing the error.

**Comment by woodaw304** [comment]
We saw something after upgrading the To Do Plug in to 0.5.0. The banner below would appear after about 30-45 minutes of activity on MM (6.3.0).  Refreshing the screen would temporarily remove the banner.  

![image](https://user-images.githubusercontent.com/98336453/151022058-d84d0c66-db40-4072-af9c-b3d2c1bfb767.png)

We checked logs and found these log messages. 

![image](https://user-images.githubusercontent.com/98336453/151021833-3ef3137a-df7a-4593-ad8c-f86b71301ad0.png)

 
Is any of this related to the problem described in the initial issue?

**Comment by mickmister** [comment]
@woodaw304 I wouldn't expect this error to occur due to anything related to the Todo plugin. Are you able to test whether or not the error occurs when the plugin is disabled? cc @hanzei

**Comment by woodaw304** [comment]
@mickmister We did not see this banner when the ToDo plug in was at version 0.3.0.  In addition, we removed the ToDo Plug in v0.5.0 and replaced with v0.4.0 and the banner issue went away.  We are running MM 6.3.1 currently.

**Comment by patrick-othmer** [comment]
We had the same issue and also the connection on client side seems to be affected on our side. As soon as we deactivated the plugin, the user online status and the notifications seems to work again properly.

**Comment by mickmister** [comment]
Adding Triage label so someone can be assigned to investigate why the todo plugin is related to the online status issue

**Comment by nough** [comment]
Same issue, same log entries, disabling todo plugin seems to have resolved user complaints.
I don't recall getting the red banner, but users would often appear as offline when returning to their laptops, and sometimes were unable to access API links such as the bigbluebutton plugin.

**Comment by nough** [comment]
> @nough - we also experienced the issue where users would appear offline. We have replaced 0.5.0 with 0.4.0, but are having other issues with the To Do plug in where it will not allow the user to select the To Do assignee.

When using v0.4.0, I am unable to use the right sidebar of the todo plugin to send a todo to someone. When I click on the "assignee" box, the mattermost screen freezes. This is true in both the desktop application and Chrome.

I can however send todos using the command line, e.g. `/todo send @woodaw304 check the contents of that bug report.`

**Comment by sanjaydemansol** [comment]
@dipak-demansol can you please try and regenerate this issue

**Comment by sstark** [comment]
> We saw something after upgrading the To Do Plug in to 0.5.0. The banner below would appear after about 30-45 minutes of activity on MM (6.3.0). Refreshing the screen would temporarily remove the banner.
> 
> ![image](https://user-images.githubusercontent.com/98336453/151022058-d84d0c66-db40-4072-af9c-b3d2c1bfb767.png)
> 
> We checked logs and found these log messages.
> 
> ![image](https://user-images.githubusercontent.com/98336453/151021833-3ef3137a-df7a-4593-ad8c-f86b71301ad0.png)
> 
> Is any of this related to the problem described in the initial issue?

We did get millions of log entries like this:

`  ... webhub.broadcast: cannot send, closing websocket for user caller="app/web_hub.go:535" user_id=12341234`

after the update, which also lead to weird behavior of some clients (offline/online changing randomly, messages not sent, messages sent twice, etc.). Disabling the todo plugin fixed it.

**Comment by larkox** [comment]
I got to the root of the problem: the websocket reconnect event.
We are passing a function that expects a message, and the websocket reconnect event has no message. This, I still don't understand how, shows as problems with other plugins, but it is always the todo plugin. A PR should come today.

**Comment by sanjaydemansol** [comment]
I checked through the problem and it is due to the websocket connection. plugin's method attach to reconnect websocket is expecting and event data and reconnection not sending one.
it was object destructuring that was causing an error. I've made some changes for that and will make PR very soon.

**Comment by mickmister** [comment]
@joebordes @nough @patrick-othmer @woodaw304 @sstark

Note that there is a fix for this is in the marketplace now with version `0.5.1`. Please upgrade the plugin on your server when you have the chance.
