### ISSUE TITLE
Be able to rank and filter todos by priority

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-todo#160]

**Comment by mickmister** [comment]
@matthewbirtch @hanzei Any thoughts on this feature?

I'm thinking we can have three levels of priority. Then the user can sort or filter on items by priority. The daily reminder could factor this in somehow as well.

This is one of the main reasons I don't use this plugin much. Most of my todos entered into the plugin are not urgent, which makes it so any urgent ones are lost in the noise. Being able to label urgent ones accordingly would let me utilize the plugin more efficiently.

**Comment by hanzei** [comment]
@mickmister This issue feels like a duplicate of https://github.com/mattermost/mattermost-plugin-todo/issues/33. There are already a lot of great comments in https://github.com/mattermost/mattermost-plugin-todo/issues/33.

What new aspects does this ticket bring up?

**Comment by mickmister** [comment]
@hanzei Yeah it mentions priority so seems to be a duplicate. I'll close this and put some thoughts there. Thanks @hanzei!
