### ISSUE TITLE
Assigned todos have disappeared

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-todo#171]
As shown in the screenshot, I am seeing that i have no todos, yet have one in the "Sent" bucket. This ticket is to investigate why the todos are not showing. It seems the API call to `plugins/com.mattermost.plugin-todo/list?list=in` is returning an empty array.

![image](https://user-images.githubusercontent.com/6913320/178533359-1a11b34e-5325-4cad-8a30-84136e3ce92d.png)

**Comment by catalintomai** [comment]
@DHaussermann or @Flinch , if you can look into this one - does it repro on other envs other than community(?).

**Comment by mickmister** [comment]
@DHaussermann Looking through the remaining GitHub triage tickets, this is the only one that stands out to me. I'm wondering if the plugin is broken for customers using this, or just on community

**Comment by mickmister** [comment]
@matthewbirtch Are you still experiencing this issue on community?

**Comment by matthewbirtch** [comment]
All good now for me @mickmister. All todos are restored for me
