### ISSUE TITLE
Adding a ToDo from a post does not move the [Permalink]

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-todo#177]
Previously when creating a To Do from a Mattermost post the `[Permalink]` is moved to a new line below the quoted text. 
Now there is no white space and the link is immediately after the text. 
![image](https://user-images.githubusercontent.com/35588783/186687309-218ecb45-4ba1-4ad8-8a17-325f50002b77.png)

This screen shows the previous and current behavior side by side.
![image](https://user-images.githubusercontent.com/35588783/186687592-eff873db-2c6c-4f48-8950-fd4189564fe6.png)
![image](https://user-images.githubusercontent.com/35588783/186688712-ab3e8189-c27e-4d67-b6d1-cadbc43cbeb8.png)

The issue is especially bothersome because trying to use the `enter` or `return` key to add the line break yourself will save the data. 0/5 of this is desirable once the bug is fixed.

**Comment by catalintomai** [comment]
Looks to be a regression; need to fix this before marketplace release.Thanks!

**Comment by asaadmahmood** [comment]
@catalintomai Submitted a PR with a fix.
