### ISSUE TITLE
ToDo no longer has markdown preview functionality 

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-todo#188]
The new UI where ToDos are created and edited no longer has away to preview any mark down in the ToDo description. 
This preview functionality used to exist as part of the older full page modal. 

![image](https://user-images.githubusercontent.com/35588783/188770726-80be097d-e435-44f4-8077-e7529216ac25.png)

**Comment by DHaussermann** [comment]
@asaadmahmood  Do you have any thoughts on this?
0/5 Not having to use the old full page modal is significantly better and it may not be urgent to put the markdown preview back in.

**Comment by asaadmahmood** [comment]
@DHaussermann That's intentional as per the design.
