### ISSUE TITLE
Feature request: only list users on your team when assigning work.

### ISSUE THREAD

**Issue by maxwux** [mattermost/mattermost-plugin-todo#196]
Only list users on your team not whole server users when assigning work.
Thank you for your dedication

**Comment by mickmister** [comment]
This should be solved by https://github.com/mattermost/mattermost-plugin-todo/pull/172. Closing this as it duplicates https://github.com/mattermost/mattermost-plugin-todo/issues/95

Thanks for reporting this @maxwux, and for being a user of Mattermost!
