### ISSUE TITLE
How to build this plugin?

### ISSUE THREAD

**Issue by rain9x** [mattermost/mattermost-plugin-todo#198]
Hi everybody,
Can anyone show me how to build this plugin? I have tried many ways but it doesn't work.

**Comment by hanzei** [comment]
`make dist` should do the trick

**Comment by mickmister** [comment]
You'll need to install node `14`, or install https://nvm.sh and run `nvm install` in the root of this repository

**Comment by rain9x** [comment]
Thanks @hanzei and @mickmister!

**Comment by mickmister** [comment]
Created ticket to document this in plugin development docs https://github.com/mattermost/mattermost-developer-documentation/issues/1222
