### ISSUE TITLE
Add TODO modal should support WYSIWIG markdown

### ISSUE THREAD

**Issue by levb** [mattermost/mattermost-plugin-todo#21]
https://github.com/mattermost/mattermost-plugin-todo/pull/20 added Markdown support to the rendering of the items, but the "edit" box in the Add modal does not support markdown yet.

**Comment by mickmister** [comment]
We can have a preview button that uses [post-utils](https://developers.mattermost.com/extend/plugins/webapp/reference/#post-utils) to render the markdown, which is how the RHS text is rendered.

https://github.com/mattermost/mattermost-plugin-todo/blob/889ce942aec27efa2fa470390202d56f0cf453ed/webapp/src/components/sidebar_right/todo_issues.jsx#L33-L34

**Comment by asimsedhain** [comment]
I would like to give this a shot.
