### ISSUE TITLE
Add Todo count and "add todo" button in LHS

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-todo#24]
#### Summary

This will look similar to the GitHub and GitLab plugin webapp components.

We can use the font-awesome `tasks` icon with the count next to it. When you click this, it should open your todos in the RHS like normal. We can then have the font-awesome `plus` icon to open the create todo modal.

#### Screenshots

How it is implemented with the GitHub plugin:
![image](https://user-images.githubusercontent.com/6913320/72359610-946acc00-36bc-11ea-9594-eb2ad1487562.png)

**Comment by thapakazi** [comment]
This addition will be a handy one :+1: 

Hi, @mickmister 
Do we have documentation/guidelines on how to build these custom UI elements?
I am new here and struggling to catch up with this just by going via other related plugings. Thanks.

**Comment by mickmister** [comment]
Hi @thapakazi! A good example can be found in the GitHub plugin [repo](https://github.com/mattermost/mattermost-plugin-github).

We can define a component in the `webapp/src/components` folder like https://github.com/mattermost/mattermost-plugin-github/tree/master/webapp/src/components/team_sidebar.

Then include in the component in the sidebar with a call to `registry.registerBottomTeamSidebarComponent` in `webapp/src/index.js` like so: https://github.com/mattermost/mattermost-plugin-github/blob/ab7832c593851ce7b55882a1325e6e64bf933bc1/webapp/src/index.js#L26

Do you have experience using React and Redux? The todo info is stored in Redux, so you will need to connect your component to the Redux store.

**Comment by larkox** [comment]
@Ashniu123 is working on this issue.
