### ISSUE TITLE
Items do not get deleted when they are no longer referenced

### ISSUE THREAD

**Issue by larkox** [mattermost/mattermost-plugin-todo#28]
When we create an item, we do two things:
- Store the item with its ID, createAt and message
- Store a reference to the item in the order list

But when we remove an item, we just remove the reference, leaving the item in the KVStore.

We should remove the item along with the reference.

**Comment by larkox** [comment]
May I take this one?

**Comment by levb** [comment]
@jwilander @aaronrothschild PM @asaadmahmood @cpoile @hanzei @larkox I have a rather radical suggestion here. What if all TODOs are self-destructing (i.e. KVSetWithExpire). 

Technical issues aside, I'm intrigued with the idea that no task should live forever. the UX could be that upon expiry, all involved users get bot-DMed; and we could add a "Bump" action to renew the expiry date (also with a DM notification).

On the technical side it'd _almost_ make everything simpler, except for the need to send the expiration-triggered messages. Now that _could_ be solved by adding a `KVKeyWillExpire` callback/hook to the plugin API. Besides solving this use case, it can be a foundation for (occasional, rare) cron jobs, cc @lieut-data - thoughts?

**Comment by jwilander** [comment]
I actually like that a lot. It would act as a forcing function to make me either actively choose the item to stay in my list or decide to take it off as not worth doing

**Comment by lieut-data** [comment]
0/5 on the TODO workflow -- still not using that as my daily driver, so not sure I fully appreciate the impact -- but at a technical level, I think this belongs squarely outside the plugin API. Maybe we can discuss more at the toolkit <> integrations sync-up?

**Comment by levb** [comment]
After discussing the idea with the toolkit team, I propose we do the following:
1. For the time being, stick with the current semantics, and merge the PR(s) from @larkox ensuring proper cleanup of deleted items.
2. File (repurpose) a ticket for Toolkit to implement a "persistent timer" for plugins, with attached state - a functional equivalent of what I proposed, but not intermixed with the existing KV expiration API.
3. Consider implementing the use case(s) inside the plugin, using the existing APIs - maybe not so difficult after all? (also a separate ticket)
