### ISSUE TITLE
Ghost entry

### ISSUE THREAD

**Issue by JtheBAB** [mattermost/mattermost-plugin-todo#3]
Hi @jwilander 

Really nice plugin. I use it on a daily base. 

Unfortunately i have one ghost entry that i can't delete:

![Image Pasted at 2019-12-6 12-17](https://user-images.githubusercontent.com/42135332/70319622-041aab00-1823-11ea-8dc9-eabb27cc12f7.png)

![Image Pasted at 2019-12-6 12-16](https://user-images.githubusercontent.com/42135332/70319624-04b34180-1823-11ea-9ed1-b7c39e795094.png)

Any way to remove that?

Because i get now a daily reminder for that :D

**Comment by jfrerich** [comment]
@JtheBAB have you tried using the `/todo pop` command? This will pop the todo issue at the top of your list. You can view the list with `/todo list`.

**Comment by JtheBAB** [comment]
Sorry. Yes @jwilander told me on community that pop exist.

**Comment by hanzei** [comment]
@JtheBAB Did it fix the issue?

**Comment by JtheBAB** [comment]
Yes. Absolutely

**Comment by hanzei** [comment]
Then I'm going to close this ticket as it's not reproachable and there is a workaround.
