### ISSUE TITLE
Render RHS todo list with markdown, so URLs can be rendered as hyperlinks

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-todo#30]
#### Summary

The webapp-side of the plugin could render its todo text as markdown with a simplified version of how the `mattermost-webapp` is rendering the markdown. The goal would be to accomplish this without importing `mattermost-webapp` in the plugin's source.

**Comment by larkox** [comment]
After [this PR](https://github.com/mattermost/mattermost-plugin-todo/pull/17) it is already doing that. Are you missing anything else?

**Comment by mickmister** [comment]
Looks like it is taken care of by that PR :) Thanks @larkox
