### ISSUE TITLE
List does not stay current if changes are made while it's open in multiple clients

### ISSUE THREAD

**Issue by jfrerich** [mattermost/mattermost-plugin-todo#34]
### Summary
If the To Do List is expanded in more than one client and edits are made, a user must close and re-open the list to see the current state in other clients.

**Steps**:

* Login to the same server from desktop and a browser (or 2 different browsers)
* Open the To Do plugin in both sessions
* From 1 session add or remove items to your To Do list

**Expected** To Do list is updated in real-time for the other session

### Additional Information

The suggested fix is to should understand/find what websocket notification is missing, and implement it.

### Ticket Link

https://mattermost.atlassian.net/browse/MM-22575

---
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team.

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/) and our [Plugins Guide](https://developers.mattermost.com/extend/plugins/).

**Comment by TheoVitkovskiy** [comment]
I will give my best shot on the weekend! (I have a long weekend starting tomorrow)

**Comment by jfrerich** [comment]
Thank you, @TheoVitkovskiy.  Let us know if you need any help!
