### ISSUE TITLE
Use Bot Account to post slash command responses

### ISSUE THREAD

**Issue by JtheBAB** [mattermost/mattermost-plugin-todo#4]
Hi @jwilander 

When i add a todo or list my todo's it doesn't show the bot logo:

![Clipboard02](https://user-images.githubusercontent.com/42135332/70319807-7be8d580-1823-11ea-9491-2bc31664801b.jpg)

**Comment by thapakazi** [comment]
Is this fixed? 
I could not reproduce this on 
 - localhost (old version: 5.17.0-rc1)
 and 
- [community mattermost](https://community.mattermost.com) (5.18.0)

**Comment by levb** [comment]
@JtheBAB can you please re-test?

**Comment by JtheBAB** [comment]
Daily Reminder is ok:
![image](https://user-images.githubusercontent.com/42135332/72713295-15b6d880-3b6d-11ea-8e7e-15110ca1ebf4.png)

/todo list not:
![image](https://user-images.githubusercontent.com/42135332/72713325-249d8b00-3b6d-11ea-8fa5-176092c42218.png)

same also on community

**Comment by hanzei** [comment]
The code :tm: states that there has never been an icon for the slash command responses: https://github.com/mattermost/mattermost-plugin-todo/blob/master/server/command.go#L46

The fix should be to us the bot account to create the slash command Responses.

**Comment by attilamolnar** [comment]
Hey, I'll take a look

**Comment by hanzei** [comment]
Awesome, thanks @attilamolnar :+1:
