### ISSUE TITLE
Handle todo message with very long connected text

### ISSUE THREAD

**Issue by jfrerich** [mattermost/mattermost-plugin-todo#41]
When a user has a message with very long text with no spaces, the text scrolls to the right. 

This an edge case that probably isn't going to be common but should be addressed.  

Looking at the image
1) very long text with scrolling issue (needs solution)
2) very long text with wrapping (correct)
3) very long HTML link that wraps correctly
![image](https://user-images.githubusercontent.com/7575921/77564682-1b90a900-6e91-11ea-8d4f-bd381c3fdfdb.png)

**Comment by TheoVitkovskiy** [comment]
I would love to do this one (would be my first frontend ticket), but I'm ok, if somebody else with less experience (less than mid-level) takes it.

**Comment by jfrerich** [comment]
@TheoVitkovskiy, it is yours!  Thanks for offering to work on this and if you have any questions feel free to ask!

**Comment by TheoVitkovskiy** [comment]
@jfrerich, I have downloaded the latest release version of the plugin, but when I try to add a todo, the form window closes, but the todo does not show up in the sidebar. It gives me the following error: "Invalid prop `todos` of type `string` supplied to `he`, expected an array.".

Am I doing something wrong, most likely I should take the latest master and somehow build it.

**Comment by TheoVitkovskiy** [comment]
@jfrerich now I've got two questions:
1. In order to see my changes, do I have to build the plugin with `make` and `deploy`?
2. When I've built the latest master (also tried it with the releaseversion), it tells me that I have no to-do issues, no matter how I add the todo. When I use the `list` command, it shows up just fine.
