### ISSUE TITLE
Please publish beta releases

### ISSUE THREAD

**Issue by aidenmitchell** [mattermost/mattermost-plugin-todo#46]
Sending a task to another user isn't something that can be done with the current release (the initial release). Publishing beta releases would help. Thanks.

**Comment by levb** [comment]
@aidenmitchell ack; we've been stuck a little on approvals, but considering it's still an early pre-release we'll cut one ASAP now.

**Comment by aidenmitchell** [comment]
Ok, great. Is there a way I can build this into a tar.gz myself so that Mattermost will accept it?

**Comment by aidenmitchell** [comment]
Also, thanks for the quick response, that's great.

**Comment by jfrerich** [comment]
@aidenmitchell, once the release is made, you will be able to get the tar.gz for mattermost.  

We don't necessarily have beta releases, but you can build the plugin into a `tar.gz` and upload it to Mattermost.  You'll need to clone the repository and `make deploy` command.  This will build the `tar.gz` from the branch you are currently on.  If you need more documentation you can also view https://developers.mattermost.com/extend/plugins/overview/

Does that answer your questions?

**Comment by aidenmitchell** [comment]
Yes, that's wonderful, thank you.

**Comment by aidenmitchell** [comment]
Update: I get an error when trying to run ```make deploy```.
```
npm ERR! Linux 4.4.0-18362-Microsoft
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/aidenmitchell/mattermost-plugin-todo/webapp/npm-debug.log
```
