### ISSUE TITLE
Several DMs from ToDo bot are no longer received

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-todo#48]
I'm seeing at least 3 cases where DMs from To Do bot are not sent to the appropriate users.

- Receiver cancels an item on their to do list >> Sender should receive a DM that receiver has canceled the task.
- Receiver marks an item on their to do list as Done  >> Sender should receive a DM that receiver has completed the task.
- Sender cancels an item that was sent >> Receiver should get a DM that the sender canceled the item

Not all DMs are missing. I can still see the DM to sender when the receiver accepts a task they have sent.  

"Add to thread" functionality is not affected by this issue. In these cases the To Do Bot will reply to the post when the event occurs.

**Comment by attilamolnar** [comment]
Hey, I'll take a look
