### ISSUE TITLE
creating a blank item

### ISSUE THREAD

**Issue by terafirmanz** [mattermost/mattermost-plugin-todo#51]
If adding a todo item by typing 
/todo add
then pressing enter by never providing any input a blank todo is added but it cannot be removed form the todo list.

**Comment by TheoVitkovskiy** [comment]
@terafirmanz Thank you for reporiting the issue.
Couldn't reproduce the issue on the latest `master`, so it has already been fixed.

**Comment by larkox** [comment]
As a workaround until new version is delivered, you can get rid of that empty todo using the slash command `/todo pop` if I am not mistaken.
