### ISSUE TITLE
Active users get a JS error and must refresh when Admin enables the plugin (intermittent)

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-todo#59]
Some users see a JS error when the plugin is enabled and must refresh to see the UI option for To Do bot. 
![EnableToDo](https://user-images.githubusercontent.com/35588783/80628720-cd3a7100-8a1f-11ea-8f77-06e8876b12b3.PNG)

I've noticed is that not all users seem to be affected and opening a new session with fresh cache does not always repro it. 
On my 2nd attempt it was actually the admin enabling the plugin that saw it and not the other user.

Possible steps:
- Uninstall To Do
- Re-install To Do (These may be optional I have no idea)
- Open 2nd browser session 
- As admin enable the plugin 
**Observed**: JS Error

**Comment by hanzei** [comment]
@larkox I'm wondering if you could take a shot at this given, which would allow us to cut a new todo plugin release and then get it into the Marketplace.
