### ISSUE TITLE
Tabs in RHS have the same style as buttons

### ISSUE THREAD

**Issue by marianunez** [mattermost/mattermost-plugin-todo#72]
In the RHS, the `Todos` and `Sent` tabs have the same look as the `Wont Do` and `Done` button which is very confusing. 

<img width="409" alt="Screen Shot 2020-06-04 at 12 52 03 PM" src="https://user-images.githubusercontent.com/936315/83788074-b6142200-a662-11ea-8f2f-9f1f259ddd1b.png">

The tabs should be styled to look more like tabs and less like buttons :)

**Comment by marianunez** [comment]
It would be great to get some UX feedback/design on this RHS overall.

**Comment by hanzei** [comment]
@asaadmahmood Do you have thoughts on this?

**Comment by asaadmahmood** [comment]
Yup, they should look something like this.
![Screenshot 2020-06-08 at 3 24 00 PM](https://user-images.githubusercontent.com/11034289/84020341-1aedb600-a99c-11ea-92e6-7e0230ef64c8.png)

**Comment by larkox** [comment]
Fixed by https://github.com/mattermost/mattermost-plugin-todo/pull/116
