### ISSUE TITLE
Improve look on different themes

### ISSUE THREAD

**Issue by larkox** [mattermost/mattermost-plugin-todo#78]
Some parts of the plugin do not react, or react in a bad manner to themes (see the screenshots attached).

We should make those parts reactive to the theme.

![Image Pasted at 2020-6-5 19-30(1)](https://user-images.githubusercontent.com/1933730/84131040-5479fc00-aa44-11ea-8049-9f21a60ccae5.png)
![Image Pasted at 2020-6-5 19-30](https://user-images.githubusercontent.com/1933730/84131044-55ab2900-aa44-11ea-81ec-8c8201cd9fe0.png)

**Comment by colorfusion** [comment]
I would like to tackle this task! 😎

**Comment by larkox** [comment]
Awesome! Thanks!
