### ISSUE TITLE
There's no way to un-select a user from the dropdown after selecting a user

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-todo#81]
When creating a todo with the full screen modal, if you have selected a user, you cannot undo your choice. We should use the `isClearable` prop with the react-select component.

**Comment by colorfusion** [comment]
I would like to work on this.

**Comment by mickmister** [comment]
Thanks @colorfusion!

**Comment by icy-meteor** [comment]
Do we have an update on this?

**Comment by mickmister** [comment]
Hi @colorfusion, how are you doing on this task? If there's any way we can help, please let us know :) We can discuss here or in the [Todo Plugin channel](https://community.mattermost.com/core/channels/plugin-todo
) on our community server.

**Comment by colorfusion** [comment]
My apologies, I was a little busy last month, I'll work on it asap within these few weeks.
