### ISSUE TITLE
Add a user preference to disallow incoming Todos

### ISSUE THREAD

**Issue by levb** [mattermost/mattermost-plugin-todo#82]
is there an option to generally disallow people to assign todos to me? I find this feature a little intrusive :/

_Issue created from a [Mattermost message](https://community-release.mattermost.com/_redirect/pl/fqoimjk93f8n7gna1efjh317jh) *by @svelle*._

**Comment by larkox** [comment]
The idea would be to add a Slash command like `/todo settings blockIncoming on/off` and then handle all the error messages when a user is trying to send a todo to someone that has this setting on.

**Comment by asimsedhain** [comment]
I would like to work on this.

**Comment by larkox** [comment]
All yours! Thanks for contributing @asimsedhain !
