### ISSUE TITLE
Permalink are not rendered in DM posts when a ToDo is received created via MM post

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-todo#84]
When a ToDo is received, that was created via a Mattermost post - ToDo Bot sends a DM with a slack-style attachment that contains a permalink to the recipient. The permalink is not being rendered correctly as a link.

![Permalink-BotPost](https://user-images.githubusercontent.com/35588783/85075181-c4e2f480-b18b-11ea-9410-f08242404a1d.PNG)

This is not a regression from v`0.2.0` It seems like we're relying on the autolink plugin to edit the post? If so, this may have been introduced some months ago when a change was made to except Bot accounts from having their posts edited by autolink in favor of bot's formatting their own posts. 

- Records on the RHS are not affected by this issue   
- ToDo items sent to other users not created via MM post are not affected
- ToDo items made for yourself are not affected as you don't receive a DM

Steps:
- Make or find a post
- Using the post menu, add a To Do based on the post
- Before saving send the To Do to another test user
- Login as the other user and see the DM

**Comment by larkox** [comment]
The actual problem is that since it is a custom post, we have to actively render the markdown. This will be solved more gracefully when we change these custom posts by Slack Attachments.
