### ISSUE TITLE
[MM-25867] Add active status to Header Icon

### ISSUE THREAD

**Issue by larkox** [mattermost/mattermost-plugin-todo#91]
Most header icons that open the RHS change their color when they have the RHS open. For example, the flagged posts or mentions.

We want Todo icon to change color also depending on the state of the RHS.

You can see a video of what we mean in the [Jira Ticket](https://mattermost.atlassian.net/browse/MM-25876)

**Comment by aidapira** [comment]
Hi @mickmister, I am working on this issue.

**Comment by larkox** [comment]
PR merged
