### ISSUE TITLE
Restrict list of recipients to team members

### ISSUE THREAD

**Issue by Hartwin2342** [mattermost/mattermost-plugin-todo#95]
It's possible to send ToDos to evry user of the server, even if direct messages being restricted to members of the users teams.
It would be really nice if the drop-down list only shows members of the team, the user is sending a ToDo from.

If this is configurable somewhere, please point me to the right place.

**Comment by hartkena** [comment]
Anyone willing to do this enhancement? We will fund it. If interested please let me know.
