### ISSUE TITLE
Make the channel header button toggle RHS instead of just show

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-todo#97]
Right now the channel header button makes the RHS open, but clicking it again does not close the RHS. Having the button toggle the RHS would have a more smooth UX.

**Comment by colorfusion** [comment]
Hey @mickmister, just wanna check with you whether anyone is working on this at the moment, I would love to give it a shot.

**Comment by mickmister** [comment]
Thanks @colorfusion! It's all yours 🙂
